// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl2qhzMQvQRI74D4cu3iHT0nBCRb0B8RU',
    appId: '1:475613852763:web:a5a13b13dcfadc1133fb7e',
    messagingSenderId: '475613852763',
    projectId: 'user-app-4567c',
    authDomain: 'user-app-4567c.firebaseapp.com',
    storageBucket: 'user-app-4567c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4uN8_hIHXTXdNAIzkTfOKqbT3PNloLnU',
    appId: '1:475613852763:android:a68c707282bd30bc33fb7e',
    messagingSenderId: '475613852763',
    projectId: 'user-app-4567c',
    storageBucket: 'user-app-4567c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1uy6hfezAPUOqMDRL7ovOXbVBO2IghS4',
    appId: '1:475613852763:ios:6cf257a0a34a973c33fb7e',
    messagingSenderId: '475613852763',
    projectId: 'user-app-4567c',
    storageBucket: 'user-app-4567c.appspot.com',
    iosBundleId: 'com.example.rblApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1uy6hfezAPUOqMDRL7ovOXbVBO2IghS4',
    appId: '1:475613852763:ios:6cf257a0a34a973c33fb7e',
    messagingSenderId: '475613852763',
    projectId: 'user-app-4567c',
    storageBucket: 'user-app-4567c.appspot.com',
    iosBundleId: 'com.example.rblApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl2qhzMQvQRI74D4cu3iHT0nBCRb0B8RU',
    appId: '1:475613852763:web:fe8da78d3ba6a53633fb7e',
    messagingSenderId: '475613852763',
    projectId: 'user-app-4567c',
    authDomain: 'user-app-4567c.firebaseapp.com',
    storageBucket: 'user-app-4567c.appspot.com',
  );
}
